name: Nuxt Generate

on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Build
      run: |
        npm install
        npm run generate

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: .output/public

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: www.valitoimisto.fi
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout to main
        uses: actions/checkout@main

      - name: Download built files
        uses: actions/download-artifact@v2.1.1
        with:
          name: production-files
          path: ./dist

      - name: Connect to server over SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_IP }} >> ~/.ssh/known_hosts

      - name: Deploy built site
        run: |
          rsync -vrm  ./dist/ ${{ secrets.SSH_LOGIN }}:/data01/virt124708/domeenid/www.valitoimisto.fi/htdocs
